# Generated by Django 3.0.8 on 2020-08-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('genres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('timestamp', models.TimeField()),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='testapi.Movie')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='testapi.User')),
            ],
        ),
    ]
