# Generated by Django 3.0.8 on 2020-08-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userratings',
            name='timestamp',
        ),
    ]
